project:
  type: website

website:
  title: "Introductory Statistics Apps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Calculators
        menu:
          - text: "Chi-squared calculator"
            href: Chi2calculator.qmd
          - text: "Effect Size Calculator"
            href: EffectSize.qmd
          - text: "Normal calculator"
            href: NormalCalculator.qmd
          - text: "Student's t calculator"
            href: Studenttcalculator.qmd
      - text: Distributions
        menu:
          - text: "Binomial Distribution"
            href: BinomialParms.qmd
          - text: "Gamma Distribution"
            href: GammaParams.qmd
          - text: "Log-normal Distribution"
            href: LogNormalParams.qmd
          - text: "Normal Distribution"
            href: NormalParams.qmd
          - text: "Poisson Distribution"
            href: PoissonParms.qmd
      - text: "Shape"
        menu:
          - text: "Old Faithful"
            href: Geyser.qmd
          - text: "Kurtosis using Boxplots"
            href: KurtosisBoxplots.qmd
          - text: "Kurtosis using Histograms"
            href: KurtosisPractice.qmd
          - text: "Kurtosis using Q-Q plots"
            href: KurtosisQQ.qmd
          - text: "Skewness using Boxplots"
            href: SkewnessBoxplot.qmd
          - text: "Skewness using Histograms"
            href: SkewnessPractice.qmd
          - text: "Skewness using Q-Q plots"
            href: SkewnessQQ.qmd
      - text: "Correlation"
        menu:
          - text: "Correlation"
            href: Correlation.qmd
          - text: "Correlation Examples"
            href: CorrelationExamples.qmd
          - text: "Correlation Practice"
            href: CorrelationExercise.qmd
          - text: "Outliers and Correlation"
            href: CorrelationOutliers.qmd
          - text: "Regression Prediction Intervals"
            href: RegressionPrediction.qmd
          - text: "Standard Errors for Slopes"
            href: SlopeStandardErrors.qmd
      - text: "Probability"
        menu:
          - text: "Conditional Probabilities"
            href: ConditionalProbability.qmd
          - text: Independence
            href: Independence.qmd
          - text: "The Rare Disease Problem"
            href: RareDisease.qmd
          - text: "Standard Deviations"
            href: StandardDeviations.qmd
      - text: "Theorems"
        menu:
          - text: "The Central Limit Theorem"
            href: CentralLimitTheroem.qmd
          - text: "The Law of Large Numbers"
            href: LawOfLargeNumbers.qmd
          - text: "The Law of Large Numbers (Animated)"
            href: LawOfLargeNumbersAnimated.qmd
      - text: Inference
        menu:
          - text: "Convidence Intervals"
            href: ConfidenceInterval.qmd
          - text: "COVID Vaccine Trials (a case study)"
            href: CovidVaccines.qmd
          - text: "Confidence Intervals and Tests"
            href: TestCI.qmd
          - text: "Vaccine Confidence Intervals"
            href: VaccineCI.qmd
          - text: "Z-scores"
            href: Z-scores.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    filters: 
      - shinylive

margin-header: |
  ![FSU-EPLS](/img/SM-White.svg)


